name: Deploy to Azure using Bicep

on:
    push:
        branches:
        - main
    
    workflow_dispatch:

permissions:
    id-token: write
    contents: write

jobs:
    changelog:
        runs-on: ubuntu-latest
        
        steps:
        - name: Generate changelog
          uses: pedrozea/generate-changelog-action@v3.1.1
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"     

    deploy:
        runs-on: ubuntu-latest

        steps:
        # Log into Azure
        - name: Login to Azure  
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

        # Run az commands
        - name: 'Run az commands'
          run: az group list
       
          
    # changelog:
    #     runs-on: ubuntu-latest
        
    #     steps:
    #     - name: Checkout code
    #       uses: actions/checkout@v2

    #     - name: conventional changelog action
    #       id: changelog
    #         # https://github.com/TriPSs/conventional-changelog-action
    #       uses: TriPSs/conventional-changelog-action@v3
    #       with:
    #         github-token: "${{ secrets.GITHUB_TOKEN }}"

    # - name: Preview Changes from Bicep
    #   uses: Azure/deployment-what-if-action@v1.0.0
    #   with:
    #     subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
    #     resourceGroup: ${{ secrets.AZURE_RG }} 
    #     templateFile: deployment/main.bicep

    # - name: Install and build Bicep
    #   run: |
    #     # Instala Bicep CLI
    #     curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
    #     chmod +x ./bicep
    #     sudo mv ./bicep /usr/local/bin/bicep
    #     bicep --version

    #     # Compila los archivos Bicep a ARM Templates
    #     bicep build main.bicep

    # - name: Deploy to Azure
    #   run: |
    #     az deployment group create --resource-group ResourceGroupName --template-file main.json
